### ISSUE TITLE
リンク時？のエラー

### ISSUE THREAD

**Issue by ghost** [tyfkda/haribote#1]
ソースコードをコンパイルするとリンク時（？）に、

ld: section .text.__x86.get_pc_thunk.bx LMA [0000000000007a4c,0000000000007a4f] overlaps section .data LMA [0000000000007a4c,000000000000939b]
../obj/fd.o: 関数 `init_dma_w' 内:
fd.c:(.text+0xa8): `_GLOBAL_OFFSET_TABLE_' に対する定義されていない参照です
../obj/fd.o: 関数 `fd_search' 内:
fd.c:(.text+0x1d2): `_GLOBAL_OFFSET_TABLE_' に対する定義されていない参照です
../obj/fd.o: 関数 `fdc_cmd' 内:
fd.c:(.text+0x23f): `_GLOBAL_OFFSET_TABLE_' に対する定義されていない参照です
../obj/fd.o: 関数 `fdc_read_results' 内:
fd.c:(.text+0x340): `_GLOBAL_OFFSET_TABLE_' に対する定義されていない参照です
../obj/fd.o: 関数 `fdc_sense_interrupt' 内:
fd.c:(.text+0x42e): `_GLOBAL_OFFSET_TABLE_' に対する定義されていない参照です
../obj/fd.o:fd.c:(.text+0x49e): `_GLOBAL_OFFSET_TABLE_' に対する定義されていない参照がさらに続いています
Makefile:39: recipe for target '../obj/bootpack.bin' failed

というエラー表示が出ます。
Windows10 + VirtualBox + Linux Mint 19
環境です。

**Comment by tyfkda** [comment]
GCCが更新されたためなのかわかりませんが、コンパイルに `-fno-pie` というオプションが必要になったようです。

kernel, apilib, apps ディレクトリ内にある Makefile の `CFLAGS`, `CXXFLAGS` に以下のように追加してみていただけますでしょうか：

```Makefile
CFLAGS+=-fno-pie
CXXFLAGS+=-fno-pie
```

**Comment by ghost** [comment]
ご返答ありがとうございます！
指定されたオプション（-fno-pie）を付けたら、リンクは通りましたが 新たに、


gcc -c -o ../obj/noodle.o -m32 -O2 --std=c99 -Wall -Wextra -Werror -nostdinc -I ../include -fno-stack-protector -fno-pie  noodle.c
noodle.c: In function ‘main’:
noodle.c:12:21: error: ‘%02d’ directive writing between 2 and 10 bytes into a region of size between 1 and 6 [-Werror=format-overflow=]
     sprintf(s, "%5d:%02d:%02d", hou, min, sec);
                     ^~~~
noodle.c:12:16: note: directive argument in the range [0, 2147483646]
     sprintf(s, "%5d:%02d:%02d", hou, min, sec);
                ^~~~~~~~~~~~~~~
noodle.c:12:16: note: directive argument in the range [0, 2147483646]
noodle.c:12:5: note: ‘sprintf’ output between 12 and 33 bytes into a destination of size 12
     sprintf(s, "%5d:%02d:%02d", hou, min, sec);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:36: recipe for target '../obj/noodle.o' failed
make[1]: *** [../obj/noodle.o] Error 1
make[1]: ディレクトリ '/home/xxxx/Documents/haribote-master/apps' から出ます


というエラーが表示されるようになってしまいました。。。

**Comment by tyfkda** [comment]
`sprintf` で `%02d` などとしていても`int`が最大で`2147483646`の幅を出力する可能性があって、それでwarningがエラーとして扱われてしまうようですね。
バッファを広げればいいかと思いましたが、考え直して`snprintf`を使うようにしてみました。
`git pull`で更新してもらえれば反映されると思います。

**Comment by ghost** [comment]
ご返答ありがとうございます。
GitHub「Haribote OS for Linux/gcc」のトップから「Download ZIP」で一括ダウンロードし、makeし直してみました！


gcc -c -o ../obj/noodle.o -m32 -O2 --std=c99 -Wall -Wextra -Werror -nostdinc -I ../include -fno-stack-protector   -fno-pie noodle.c
noodle.c: In function ‘main’:
noodle.c:12:33: error: ‘%02d’ directive output may be truncated writing between 2 and 10 bytes into a region of size between 9 and 14 [-Werror=format-truncation=]
     snprintf(s, sizeof(s), "%5d:%02d:%02d", hou, min, sec);
                                 ^~~~
noodle.c:12:28: note: directive argument in the range [0, 2147483646]
     snprintf(s, sizeof(s), "%5d:%02d:%02d", hou, min, sec);
                            ^~~~~~~~~~~~~~~
noodle.c:12:28: note: directive argument in the range [0, 2147483646]
noodle.c:12:5: note: ‘snprintf’ output between 12 and 33 bytes into a destination of size 20
     snprintf(s, sizeof(s), "%5d:%02d:%02d", hou, min, sec);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:38: recipe for target '../obj/noodle.o' failed
make[1]: *** [../obj/noodle.o] Error 1
make[1]: ディレクトリ '/home/xxxx/Documents/haribote-master/apps' から出ます


やはり、「noodle.c」の辺りで止まってしまいます。。。

**Comment by tyfkda** [comment]
`snprintf`でも警告が出てしまうんですね。ひとまず警告を無視するよう、`CFLAGS`や`CXXFLAGS`から`-Werror`を外して試してもらえますか？

**Comment by ghost** [comment]
返信ありがとうございます。

指定されたオプション（Werror）を外したら「haribote.iso」が作成され、VirtualBoxから起動することができました！

OSを自作するには、コンパイラやリンカの知識がとても重要なんですね。

tyfkdaさんの書かれたコードと「30日でできる！OS自作入門」の本を見比べながら、これから勉強していきたいと思います！

**Comment by tyfkda** [comment]
無事ビルドできて実際に動いたようで、よかったです。
gitのHEADだとソースもそれなりにでかくて追うのも辛いと思うので、
gitで[tagが打ってある](https://github.com/tyfkda/haribote/releases)ので過去の状態を見てもらうと良いかもしれません。
